# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 822)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.central_widget = QtWidgets.QWidget(self.centralwidget)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_bar = QtWidgets.QWidget(self.central_widget)
        self.time_bar.setMinimumSize(QtCore.QSize(0, 200))
        self.time_bar.setMaximumSize(QtCore.QSize(16777215, 200))
        self.time_bar.setObjectName("time_bar")
        self.remaining_time_bar = QtWidgets.QProgressBar(self.time_bar)
        self.remaining_time_bar.setGeometry(QtCore.QRect(310, 120, 241, 23))
        self.remaining_time_bar.setStyleSheet("*{\n"
"    border-radius: 12px;\n"
"    text-align: center;\n"
"    font: 87 10pt \"Arial Black\";\n"
"}")
        self.remaining_time_bar.setProperty("value", 24)
        self.remaining_time_bar.setObjectName("remaining_time_bar")
        self.label = QtWidgets.QLabel(self.time_bar)
        self.label.setGeometry(QtCore.QRect(110, 20, 151, 31))
        self.label.setStyleSheet("*{\n"
"font: 16pt \"Game Of Squids\";\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.time_bar)
        self.widget = QtWidgets.QWidget(self.central_widget)
        self.widget.setObjectName("widget")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 160, 76, 72))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets\\settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout.addWidget(self.central_widget, 1, 0, 1, 1)
        self.top_menu = QtWidgets.QWidget(self.centralwidget)
        self.top_menu.setMinimumSize(QtCore.QSize(11, 30))
        self.top_menu.setMaximumSize(QtCore.QSize(16777215, 30))
        self.top_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.top_menu.setObjectName("top_menu")
        self.time_label = QtWidgets.QLabel(self.top_menu)
        self.time_label.setGeometry(QtCore.QRect(690, 10, 47, 16))
        self.time_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.top_menu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kids Mode"))
        self.time_label.setText(_translate("MainWindow", "time"))
